In [1]:
import pandas as pd
df1 = pd.read_csv("ALL_Data_withGene1_withID_S.csv")
df2 = pd.read_csv("Human_SL.csv")

In [2]:
df2

,id,n1.name,n1.identifier,n2.name,n2.identifier,r.cell_line,r.pubmed_id,r.source,r.statistic_score
0,0,TMEM35A,59353,PTEN,5728,NaN,26427375,Computational Prediction,0.300
1,1,TMEM35A,59353,BRCA2,675,NaN,26427375,Computational Prediction,0.300
2,2,CIDEA,1149,NAE1,8883,A375,23100467,GenomeRNAi,0.500
3,3,FHL5,9457,OPRK1,4986,NaN,25171417,Computational Prediction,0.300
4,4,FHL5,9457,GHRHR,2692,NaN,25171417,Computational Prediction,0.300
...,...,...,...,...,...,...,...,...,...
35938,35938,PRKCQ,5588,SLC22A1,6580,K562;K562,20609354,GenomeRNAi,0.521
35939,35939,RNF19A,25897,TP53,7157,NaN,26427375,Computational Prediction,0.300
35940,35940,SLC10A7,84068,ATM,472,NaN,26427375,Computational Prediction,0.300
35941,35941,SVIL,6840,PTEN,5728,NaN,26427375,Computational Prediction,0.300
35942,35942,SVIL,6840,CAV2,858,NaN,25171417,Computational Prediction,0.300

In [3]:
df2_pairs = list(zip(df2['n1.identifier'], df2['n2.identifier']))

In [4]:
df1

,id,Cell Line name,Tissue,gene_1,Anchor Target,Anchor Pathway,gene_2,library Target,Library Pathway,Synergy?,source,ZIP,Bliss,Loewe,HSA,ZIPclassification,blissclassification,loeweclassification,hsaclassification,Gene
0,0,L1236,Lymphoid,2-FLUORO ARA-A,1633;5422;6311;4780;4088;2740;6241;6240;140;34...,NaN,BORTEZOMIB,1565;1544;1576;1559;1557;5689;5693;5243;28234;...,NaN,synergy,NaN,10.270,9.610,1.580,4.720,1.0,1.0,1.0,1.0,340273;8038;11093;55811;213;220;55107;411;472;...
1,1,L1236,Lymphoid,2-FLUORO ARA-A,1633;5422;6311;4780;4088;2740;6241;6240;140;34...,NaN,DISULFIRAM,1577;1576;1571;217;1621;8647;1621;3028;54737;1...,NaN,synergy,NaN,140.720,135.620,9.410,10.030,1.0,1.0,1.0,1.0,340273;8038;11093;55811;213;220;55107;411;472;...
2,5,L1236,Lymphoid,2-FLUORO ARA-A,1633;5422;6311;4780;4088;2740;6241;6240;140;34...,NaN,VINCRISTINE,1577;1576;1551;203068;7277;8647;4363;10599;524...,NaN,synergy,NaN,8.190,10.150,5.000,3.980,1.0,1.0,1.0,1.0,340273;8038;11093;55811;213;220;55107;411;472;...
3,7,TC71,Bone,2-METHOXYESTRADIOL,6462;1545;1312;1588;3091;1543,NaN,BARDOXOLONE METHYL,4792,NaN,synergy,NaN,27.854,25.973,4.795,8.534,1.0,1.0,1.0,1.0,19;11093;11096;154796;270;29028;773;774;790;92...
4,9,TC71,Bone,2-METHOXYESTRADIOL,6462;1545;1312;1588;3091;1543,NaN,EVEROLIMUS,1565;1576;2475;10599;5243;6579;28234;2475;5243...,NaN,synergy,NaN,21.597,17.616,8.354,10.189,1.0,1.0,1.0,1.0,19;11093;11096;154796;270;29028;773;774;790;92...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23065,164491,MOLT4,Lymphoid,ZOLINZA,4780;7849;190;1080;51053;9611;390245;55869;515...,NaN,VINBLASTINE SULFATE,3725;51175;7283;51174;203068;7846;6916;89845;1...,NaN,synergy,ALMANAC,9.990,10.260,2.690,0.800,1.0,1.0,1.0,1.0,10058;26090;7920;57406;25;27;32;1636;43;47;109...
23066,164492,NCIH23,Lung,ZOLINZA,4780;7849;190;1080;51053;9611;390245;55869;515...,NaN,VINBLASTINE SULFATE,3725;51175;7283;51174;203068;7846;6916;89845;1...,NaN,synergy,ALMANAC,1.720,3.220,4.070,0.350,1.0,1.0,1.0,1.0,18;19;340273;31;32;1636;57007;8751;6868;11093;...
23067,164495,RPMI8226,Lymphoid,ZOLINZA,4780;7849;190;1080;51053;9611;390245;55869;515...,NaN,VINBLASTINE SULFATE,3725;51175;7283;51174;203068;7846;6916;89845;1...,NaN,synergy,ALMANAC,2.200,7.870,8.140,2.890,1.0,1.0,1.0,1.0,55811;213;27329;8639;29028;6311;659;8911;785;8...
23068,164498,SNB75,CNS/Brain,ZOLINZA,4780;7849;190;1080;51053;9611;390245;55869;515...,NaN,VINBLASTINE SULFATE,3725;51175;7283;51174;203068;7846;6916;89845;1...,NaN,synergy,ALMANAC,0.510,1.280,0.760,0.270,1.0,1.0,1.0,1.0,340273;89845;57406;1636;249;154796;50807;613;7...
23069,164500,A498,Kidney,ZOLINZA,4780;7849;190;1080;51053;9611;390245;55869;515...,NaN,ZOLEDRONIC ACID,2224;9453;4363;4317;4313;4323;9453;2224;768;76...,NaN,synergy,ALMANAC,0.740,1.490,1.320,2.100,1.0,1.0,1.0,1.0,5243;1109;238;154796;317;324;405;55870;25825;8...

In [5]:
df1_expanded = df1.copy()
df1_expanded['Anchor Target'] = df1_expanded['Anchor Target'].apply(lambda x: x.split(','))
df1_expanded['library Target'] = df1_expanded['library Target'].apply(lambda x: x.split(','))
df1_expanded

,id,Cell Line name,Tissue,gene_1,Anchor Target,Anchor Pathway,gene_2,library Target,Library Pathway,Synergy?,source,ZIP,Bliss,Loewe,HSA,ZIPclassification,blissclassification,loeweclassification,hsaclassification,Gene
0,0,L1236,Lymphoid,2-FLUORO ARA-A,[1633;5422;6311;4780;4088;2740;6241;6240;140;3...,NaN,BORTEZOMIB,[1565;1544;1576;1559;1557;5689;5693;5243;28234...,NaN,synergy,NaN,10.270,9.610,1.580,4.720,1.0,1.0,1.0,1.0,340273;8038;11093;55811;213;220;55107;411;472;...
1,1,L1236,Lymphoid,2-FLUORO ARA-A,[1633;5422;6311;4780;4088;2740;6241;6240;140;3...,NaN,DISULFIRAM,[1577;1576;1571;217;1621;8647;1621;3028;54737;...,NaN,synergy,NaN,140.720,135.620,9.410,10.030,1.0,1.0,1.0,1.0,340273;8038;11093;55811;213;220;55107;411;472;...
2,5,L1236,Lymphoid,2-FLUORO ARA-A,[1633;5422;6311;4780;4088;2740;6241;6240;140;3...,NaN,VINCRISTINE,[1577;1576;1551;203068;7277;8647;4363;10599;52...,NaN,synergy,NaN,8.190,10.150,5.000,3.980,1.0,1.0,1.0,1.0,340273;8038;11093;55811;213;220;55107;411;472;...
3,7,TC71,Bone,2-METHOXYESTRADIOL,[6462;1545;1312;1588;3091;1543],NaN,BARDOXOLONE METHYL,[4792],NaN,synergy,NaN,27.854,25.973,4.795,8.534,1.0,1.0,1.0,1.0,19;11093;11096;154796;270;29028;773;774;790;92...
4,9,TC71,Bone,2-METHOXYESTRADIOL,[6462;1545;1312;1588;3091;1543],NaN,EVEROLIMUS,[1565;1576;2475;10599;5243;6579;28234;2475;524...,NaN,synergy,NaN,21.597,17.616,8.354,10.189,1.0,1.0,1.0,1.0,19;11093;11096;154796;270;29028;773;774;790;92...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23065,164491,MOLT4,Lymphoid,ZOLINZA,[4780;7849;190;1080;51053;9611;390245;55869;51...,NaN,VINBLASTINE SULFATE,[3725;51175;7283;51174;203068;7846;6916;89845;...,NaN,synergy,ALMANAC,9.990,10.260,2.690,0.800,1.0,1.0,1.0,1.0,10058;26090;7920;57406;25;27;32;1636;43;47;109...
23066,164492,NCIH23,Lung,ZOLINZA,[4780;7849;190;1080;51053;9611;390245;55869;51...,NaN,VINBLASTINE SULFATE,[3725;51175;7283;51174;203068;7846;6916;89845;...,NaN,synergy,ALMANAC,1.720,3.220,4.070,0.350,1.0,1.0,1.0,1.0,18;19;340273;31;32;1636;57007;8751;6868;11093;...
23067,164495,RPMI8226,Lymphoid,ZOLINZA,[4780;7849;190;1080;51053;9611;390245;55869;51...,NaN,VINBLASTINE SULFATE,[3725;51175;7283;51174;203068;7846;6916;89845;...,NaN,synergy,ALMANAC,2.200,7.870,8.140,2.890,1.0,1.0,1.0,1.0,55811;213;27329;8639;29028;6311;659;8911;785;8...
23068,164498,SNB75,CNS/Brain,ZOLINZA,[4780;7849;190;1080;51053;9611;390245;55869;51...,NaN,VINBLASTINE SULFATE,[3725;51175;7283;51174;203068;7846;6916;89845;...,NaN,synergy,ALMANAC,0.510,1.280,0.760,0.270,1.0,1.0,1.0,1.0,340273;89845;57406;1636;249;154796;50807;613;7...
23069,164500,A498,Kidney,ZOLINZA,[4780;7849;190;1080;51053;9611;390245;55869;51...,NaN,ZOLEDRONIC ACID,[2224;9453;4363;4317;4313;4323;9453;2224;768;7...,NaN,synergy,ALMANAC,0.740,1.490,1.320,2.100,1.0,1.0,1.0,1.0,5243;1109;238;154796;317;324;405;55870;25825;8...

In [6]:
def check_pairs(row, pairs):
    a_components = row['Anchor Target']
    b_components = row['library Target']
    for a_comp in a_components:
        for b_comp in b_components:
            if (a_comp, b_comp) in pairs or (b_comp, a_comp) in pairs:
                return 'y'
    return 'n'

# 添加匹配结果列
df1['match'] = df1_expanded.apply(check_pairs, axis=1, args=(df2_pairs,))
df1

Traceback (most recent call last):
  File "_pydevd_bundle/pydevd_cython.pyx", line 1078, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 297, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "D:\soft\Anaconda\lib\site-packages\debugpy\_vendored\pydevd\pydevd.py", line 1976, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "D:\soft\Anaconda\lib\site-packages\debugpy\_vendored\pydevd\pydevd.py", line 2011, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt

KeyboardInterrupt:

In [10]:
n_count = df1['match'].value_counts().get('n', 0)

print(f"不满足条件的行数: {n_count}")

不满足条件的行数: 23070

In [12]:
df2

,id,n1.name,n1.identifier,n2.name,n2.identifier,r.cell_line,r.pubmed_id,r.source,r.statistic_score
0,0,TMEM35A,59353,PTEN,5728,NaN,26427375,Computational Prediction,0.300
1,1,TMEM35A,59353,BRCA2,675,NaN,26427375,Computational Prediction,0.300
2,2,CIDEA,1149,NAE1,8883,A375,23100467,GenomeRNAi,0.500
3,3,FHL5,9457,OPRK1,4986,NaN,25171417,Computational Prediction,0.300
4,4,FHL5,9457,GHRHR,2692,NaN,25171417,Computational Prediction,0.300
...,...,...,...,...,...,...,...,...,...
35938,35938,PRKCQ,5588,SLC22A1,6580,K562;K562,20609354,GenomeRNAi,0.521
35939,35939,RNF19A,25897,TP53,7157,NaN,26427375,Computational Prediction,0.300
35940,35940,SLC10A7,84068,ATM,472,NaN,26427375,Computational Prediction,0.300
35941,35941,SVIL,6840,PTEN,5728,NaN,26427375,Computational Prediction,0.300
35942,35942,SVIL,6840,CAV2,858,NaN,25171417,Computational Prediction,0.300

In [15]:
df2.at[0, 'n1.identifier'] = '1633'
df2.at[0, 'n2.identifier'] = '1565'
df2

,id,n1.name,n1.identifier,n2.name,n2.identifier,r.cell_line,r.pubmed_id,r.source,r.statistic_score
0,0,TMEM35A,1633,PTEN,1565,NaN,26427375,Computational Prediction,0.300
1,1,TMEM35A,59353,BRCA2,675,NaN,26427375,Computational Prediction,0.300
2,2,CIDEA,1149,NAE1,8883,A375,23100467,GenomeRNAi,0.500
3,3,FHL5,9457,OPRK1,4986,NaN,25171417,Computational Prediction,0.300
4,4,FHL5,9457,GHRHR,2692,NaN,25171417,Computational Prediction,0.300
...,...,...,...,...,...,...,...,...,...
35938,35938,PRKCQ,5588,SLC22A1,6580,K562;K562,20609354,GenomeRNAi,0.521
35939,35939,RNF19A,25897,TP53,7157,NaN,26427375,Computational Prediction,0.300
35940,35940,SLC10A7,84068,ATM,472,NaN,26427375,Computational Prediction,0.300
35941,35941,SVIL,6840,PTEN,5728,NaN,26427375,Computational Prediction,0.300
35942,35942,SVIL,6840,CAV2,858,NaN,25171417,Computational Prediction,0.300

In [ ]:
def check_pairs(row, pairs):
    a_components = row['Anchor Target']
    b_components = row['library Target']
    for a_comp in a_components[0]:
        for b_comp in b_components[0]:
            if (a_comp, b_comp) in pairs or (b_comp, a_comp) in pairs:
                return 'y'
    return 'n'

# 添加匹配结果列
df1['match'] = df1_expanded.apply(check_pairs, axis=1, args=(df2_pairs,))
df1

In [18]:
n_count = df1['match'].value_counts().get('n', 0)

print(f"不满足条件的行数: {n_count}")

不满足条件的行数: 23070